name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Updated to a more recent Node.js version for compatibility

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage
        continue-on-error: true # Allows the workflow to proceed even if tests fail

      - name: Debug Coverage Directory
        run: |
          echo "Checking coverage directory contents"
          ls -la coverage

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
          fail-on-error: false # Ensures the workflow does not fail if coverage upload fails

